version: "2"
services:
  nginx:
    image: nginx
    ports:
      - "9301:80"
    volumes:
      - ./example:/usr/share/nginx/html:ro
  streamer:
    build: .
    image: rtsp-streamer
    ports:
      - "9300:9300"
    environment:
      - STREAM_URL=rtsp://192.168.10.32:8554/ds-test
      - STREAM_NAME="Docker Stream"
    volumes:
      - ./src:/src